### PR TITLE
set button contained

### PR DESCRIPTION
**Pull request by Mkohm**
Resolves https://github.com/GlobalDigitalLibraryio/issues/issues/418

### CODE REVIEW

**Comment by Mkohm** [comment]
Liker ikke helt at "More" knappen under featured content blir seendes ut helt lik som "More" knappen i boklisten. Dette kan potensielt være forvirrende siden knappene ser like ut. Jeg synes ikke outlining av knappen så bra ut.

**Comment by Mkohm** [comment]
outlined
contained

**Comment by Mkohm** [comment]
inverted

**Comment by alexanbj** [comment]
Closed in favor of https://github.com/GlobalDigitalLibraryio/gdl-frontend/pull/275

**Pull request closed without merging**
